version: "3.4"

services:
  dev:
    container_name: interview_api_dev
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: development
      args:
        - PORT=${PORT}
        - NODE_ENV=${NODE_ENV}
    command: npm run start:debug
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongodb
    networks:
      - mynet

  mongodb:
    container_name: ${MONGO_HOST}
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - ./docker/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - mongo-storage:/data/db
    networks:
      - mynet

volumes:
  mongo-storage: {}

networks:
  mynet: